config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :payees do
    resources :schedules, shallow: true, except: :index do
      resources :payments, shallow: true, except: %i[index show]
    end
  end

  get 'calendar', to: 'calendar#index'
  get 'calendar/events', to: 'calendar#events'
  get 'payments', to: 'payments#index'

  root 'calendar#index'
end

app/models/schedule.rb
# frozen_string_literal: true

# Model for schedules
class Schedule < ApplicationRecord
  strip_attributes

  # Relations
  belongs_to :payee
  has_many :payments, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :start_date, presence: true, date: true,
                         format: { with: %r{\A\d*/(0[1-9]|1[0-9]|2[0-8])/\d*\z},
                                   message: 'must be on or before the 28th' }
  validates :end_date, date: { after: :start_date, allow_blank: true }
  validates :frequency, inclusion: { in: ->(_a) { frequencies.keys },
                                     message: 'must be from dropdown list' }
  validates :payee_id, presence: true, numericality: { only_integer: true }

  # Custom validators
  validate :cannot_modify_start_date_when_payments_exist
  validate :end_date_must_be_after_last_payment
  validate :autopay_requires_minimum_payment

  def autopay_requires_minimum_payment
    return if minimum_payment.present? || !autopay?

    errors.add(:autopay, 'requires a value for minimum payment')
  end

  def cannot_modify_start_date_when_payments_exist
    return if payments.empty? || start_date_was == start_date

    errors.add(:start_date, 'cannot be changed if payments exist')
  end

  def end_date_must_be_after_last_payment
    return if end_date.blank? || payments.empty?
    return if end_date > payments.order(due_date: :desc).first.due_date

    errors.add(:end_date, 'must be after last payment due date')
  end

  def self.frequencies
    { # Week-based frequencies
      'weekly' => { description: 'Once every week', frequency: 'weekly', interval: 1 },
      'biweekly' => { description: 'Once every two weeks', frequency: 'weekly', interval: 2 },
      'quadweekly' => { description: 'Once every three weeks', frequency: 'weekly', interval: 4 },

      # Month-based frequencies
      'monthly' => { description: 'Once every month', frequency: 'monthly', interval: 1 },
      'bimonthly' => { description: 'Once every two months', frequency: 'monthly', interval: 2 },
      'semimonthly' => { description: 'Twice every month', frequency: 'monthly', interval: 1 },
      'trimonthly' => { description: 'Quarterly (once every four months)', frequency: 'monthly',
                        interval: 3 },

      # Year-based frequencies
      'annually' => { description: 'Once every year', frequency: 'yearly', interval: 1 },
      'semiannually' => { description: 'Twice every year', frequency: 'yearly', interval: 1 }
    }.freeze
  end

  def rrule_string
    [rrule_dtstart, rrule_until, rrule_frequency, rrule_interval, rrule_semimonthly_bymonthdays,
     rrule_semiannually_bymonth].compact.join(';')
  end

  def generate_autopayments
    today = Time.zone.today
    payments = schedule.payments
    Schedule.each do |schedule|
      continue if !schedule.active? || payments.where(due_date: today).any? ||
                  !recurrence_date?(today)
      payments.create(due_date: today, date: today, amount: schedule.minimum_payemnt,
                      comment: 'Created by autopay')
    end
  end

  def recurrence_date?(date)
    rrule.between((date - 1.day).to_datetime, (date + 1.day).to_datetime).include? date
  end

  def active?(date = nil)
    date = Time.zone.today if date.nil?
    date >= start_date && (end_date.nil? || date <= end_date)
  end

  private

  def rrule
    dateparts = [start_date.year, start_date.month, start_date.day]
    RRule.parse(rrule_string, dtstart: Time.zone.local(*dateparts))
  end

  def rrule_dtstart
    "DTSTART=#{rrule_date_format(start_date)}"
  end

  def rrule_until
    return nil if end_date.blank?

    "UNTIL=#{rrule_date_format(end_date)}"
  end

  def rrule_date_format(date)
    date.strftime('%Y%m%dT%H%M%S')
  end

  def rrule_frequency
    "FREQ=#{Schedule.frequencies[frequency][:frequency].upcase}"
  end

  def rrule_interval
    "INTERVAL=#{Schedule.frequencies[frequency][:interval]}"
  end

  def rrule_semimonthly_bymonthdays
    return nil if frequency != 'semimonthly'

    start_day = start_date.day
    match_day = start_day > 14 ? start_day - 14 : start_day + 14
    "BYMONTHDAY=#{start_day},#{match_day}"
  end

  def rrule_semiannually_bymonth
    return nil if frequency != 'semiannually'

    start_month = start_date.month
    match_month = start_month > 6 ? start_month - 6 : start_month + 6
    "BYMONTH=#{start_month},#{match_month}"
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

# Conroller for creating/editing schedules
class SchedulesController < ApplicationController
  before_action :set_payee, only: %i[new create]
  before_action :set_schedule, only: %i[edit update destroy show]
  before_action only: %i[update create] do
    convert_to_sql_dates(%i[start_date end_date])
  end

  # GET /payees/1/schedules/new
  def new
    @schedule = Schedule.new
    @schedule.payee = @payee
  end

  # GET /schedules/1
  def show
    @schedule = @schedule.decorate
    @payments = @schedule.payments
                         .rezort(params[:sort], 'date ASC')
                         .page(params[:page])
                         .decorate
  end

  # GET /schedules/1/edit
  def edit; end

  # POST /schedules
  # POST /schedules.json
  # rubocop: disable Metrics/AbcSize
  def create
    @schedule = Schedule.new(schedule_params).tap { |schedule| schedule.payee_id = @payee.id }

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @payee, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop: enable Metrics/AbcSize

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    payee = @schedule.payee
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to payee, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payee
    @payee = Payee.find(params[:payee_id])
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(
      :name,
      :start_date,
      :end_date,
      :frequency,
      :autopay,
      :minimum_payment
    )
  end
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

# These helpers used in views for schedules
module SchedulesHelper
  def grouped_frequencies
    [
      ['Weekly', Schedule.frequencies
                         .select { |k| k.include? 'weekly' }
                         .map { |k, v| [k, v[:description]] }],
      ['Monthly', Schedule.frequencies
                          .select { |k| k.include? 'monthly' }
                          .map { |k, v| [k, v[:description]] }],
      ['Annually', Schedule.frequencies
                           .select { |k| k.include? 'annually' }
                           .map { |k, v| [k, v[:description]] }]
    ]
  end

  def schedule_delete_modal_params
    { confirm: 'Deleting this schedule will also permanently delete all associated historical ' \
               'payments. Are you sure you want to delete this schedule?',
      commit: 'Delete Schedule' }
  end
end

app/views/schedules/_form.html.slim
= simple_form_for([payee, schedule]) do |f|
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :start_date, append: icon('calendar-alt')
    = f.input :end_date, append: icon('calendar-alt')
    = f.input :frequency, as: :grouped_select,
                          prompt: 'Select a payment frequency',
                          collection: grouped_frequencies,
                          group_method: :last,
                          group_label_method: :first,
                          label_method: :last,
                          value_method: :first

    = f.input :minimum_payment, wrapper: :horizontal_input_group, prepend: icon('dollar-sign'),
      input_html: { value: number_with_precision(f.object.minimum_payment, precision: 2) }
    = f.input :autopay

  .form-actions
    .form-group.row.mb-0
      .col-sm-9.offset-sm-3
        = f.button :submit, class: 'btn-primary'
        = button_reset
        - if schedule.persisted?
          = button_cancel schedule, 'Back to Schedule Details'
        - else
          = button_cancel payee, 'Back to Payee Details'

app/views/schedules/_index.html.slim
.card
  .card-header
    .d-flex
      .h4.mr-auto Schedules
      = button_success 'New Schedule', new_payee_schedule_path(payee), 'plus'

  .card-body.p-0
    - if schedules.any?
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.table-sm
          thead.thead-light
            tr
              th = sortable 'Name', :name
              th = sortable 'Start Date', :start_date
              th = sortable 'End Date', :end_date
              th = sortable 'Frequency', :frequency
              th = sortable 'Autopay', :autopay
              th = sortable 'Minimum Payment', :minimum_payment
              th Actions
          tbody
            - schedules.each do |schedule|
              tr
                td = schedule.name
                td = schedule.start_date
                td = schedule.end_date
                td = schedule.frequency
                td = schedule.autopay
                td.text-right = schedule.minimum_payment
                td.text-nowrap
                  = button_primary 'Details', schedule_path(schedule), 'info-circle'
        = paginate schedules
    - else
      .h5.text-center.p-3 There are currently no schedules for this payee.

app/views/schedules/edit.html.slim
.card
  .card-header
    .d-flex
      .h4 Schedule
  .card-body
    == render partial: 'form', locals: { payee: @payee, schedule: @schedule }

app/views/schedules/new.html.slim
.card
  .card-header
    .h4 = ('New Schedule for ' + @payee.name)
  .card-body
    == render partial: 'form', locals: { payee: @payee, schedule: @schedule }

app/views/schedules/show.html.slim
.card
  .card-header
    .h4 Schedule Details
  .card-body
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('name')
      .col-sm-9.form-control-plaintext = @schedule.name
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('start_date')
      .col-sm-9.form-control-plaintext = @schedule.start_date
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('end_date')
      .col-sm-9.form-control-plaintext = @schedule.end_date
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('frequency')
      .col-sm-9.form-control-plaintext = @schedule.frequency
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('autopay')
      .col-sm-9.form-control-plaintext = @schedule.autopay
    .form-group.row
      .col-sm-3.col-form-label = Schedule.human_attribute_name('minimum_payment')
      .col-sm-9.form-control-plaintext = @schedule.minimum_payment
    .form-group.row
      .col-sm-9.offset-sm-3
        = button_primary 'Edit Schedule', edit_schedule_path(@schedule), 'edit'
        = button_danger 'Delete Schedule', @schedule, 'trash',
          data: schedule_delete_modal_params, method: :delete
        = button_cancel payee_path(@schedule.payee), 'Back to Payee Details'

br

= render partial: 'payments/index', locals: { payments: @payments, schedule: @schedule }