config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :payees do
    resources :schedules, shallow: true, except: :index do
      resources :payments, shallow: true, except: %i[index show]
    end
  end

  get 'calendar', to: 'calendar#index'
  get 'calendar/events', to: 'calendar#events'
  get 'payments', to: 'payments#index'

  root 'calendar#index'
end

app/models/payment.rb
# frozen_string_literal: true

# Payment model
class Payment < ApplicationRecord
  strip_attributes

  # Relations
  belongs_to :schedule

  # Validations
  validates :schedule_id, presence: true
  validates :date, date: true, presence: true
  validates :due_date, date: true, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  # Custom validator
  validate :due_date_after_start_date
  validate :due_date_before_end_date
  validate :due_date_must_be_valid_recurrence_date

  def due_date_after_start_date
    return if !schedule || !due_date || due_date >= schedule.start_date

    errors.add(:due_date, 'must be after schedule start date')
  end

  def due_date_before_end_date
    return if !schedule || !due_date || schedule.end_date.blank? || due_date <= schedule.end_date

    errors.add(:due_date, 'must be before schedule end date')
  end

  def due_date_must_be_valid_recurrence_date
    return if !schedule || !due_date
    return if schedule.recurrence_date? due_date

    errors.add(:due_date, 'must be on a valid schedule recurrence date')
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

# Handles creation of payments
class PaymentsController < ApplicationController
  before_action :set_schedule, only: %i[new create]
  before_action :set_payment, only: %i[edit update destroy]
  before_action only: %i[update create] do
    convert_to_sql_dates(%i[date due_date])
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @payment.schedule = @schedule
  end

  # GET /payments/
  def index
    @payments = Payment.select('payments.*, schedules.name as schedule, payees.name as payee')
                       .joins(schedule: :payee)
                       .includes(schedule: :payee)
                       .rezort(params[:sort], 'date DESC')
                       .page(params[:page])
                       .decorate
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments
  # POST /payments.json
  # rubocop: disable Metrics/AbcSize
  def create
    @payment = Payment.new(payment_params).tap { |payment| payment.schedule_id = @schedule.id }

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment.schedule, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop: enable Metrics/AbcSize

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment.schedule, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    schedule = @payment.schedule
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to schedule, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def set_schedule
    @schedule = Schedule.find(params[:schedule_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:schedule_id, :amount, :date, :comment, :due_date)
  end
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

# These helpers used in views for payments
module PaymentsHelper
  def payment_delete_modal_params
    { confirm: 'Are you sure you want to permanently delete this payment?',
      commit: 'Delete Payment' }
  end
end

app/views/payments/_form.html.slim
- if payment.schedule.autopay?
  .alert.alert-warning
    | This schedule is currently configured for autopay. Automatic payment will be skipped for
     due date if a manual payment is created.
= simple_form_for([schedule, payment], wrapper: :horizontal_form) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :date, append: icon('calendar-alt')
    = f.input :due_date, append: icon('calendar-alt'),
                         input_html: { data: { rrule: f.object.schedule.rrule_string } }
    - if payment.schedule.minimum_payment.present?
      .form-group.row.m-0.p-0
        .offset-sm-3.col-sm-9
          small
            ' Minimum Payment for this schedule is:
            = number_to_currency(payment.schedule.minimum_payment)
    = f.input :amount, wrapper: :horizontal_input_group, prepend: icon('dollar-sign'),
      input_html: {value: number_with_precision(f.object.amount, precision: 2) }
    = f.input :comment

  .form-actions
    .form-group.row.mb-0
      .col-sm-9.offset-sm-3
        = f.button :submit, class: 'btn-primary'
        = button_reset
        = button_cancel payment.schedule, 'Back to Schedule'

app/views/payments/_index.html.slim
.card
  .card-header
    .d-flex
      .h4.mr-auto Payments
      = button_success 'New Payment', new_schedule_payment_path(schedule), 'plus'

  .card-body.p-0
    - if payments.any?
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.table-sm
          thead.thead-light
            tr
              th = sortable 'Date', :Date
              th = sortable 'Due Date', :due_date
              th = sortable 'Amount', :amount
              th = sortable 'Comment', :comment
              th Actions
          tbody
            - payments.each do |payment|
              tr
                td = payment.date
                td = payment.due_date
                td.text-right = payment.amount
                td = payment.comment
                td.text-nowrap
                  = button_primary 'Edit Payment', edit_payment_path(payment), 'edit'
                  = button_danger 'Delete Payment', payment, 'trash',
                      data: payment_delete_modal_params, method: :delete
        = paginate  payments
    - else
      .h5.text-center.p-3 There are currenty no paymens for this schedule.

app/views/payments/edit.html.slim
.card
  .card-header
    .d-flex
      .h4 Payment
  .card-body
    == render partial: 'form', locals: { payment: @payment, schedule: @schedule }

app/views/payments/index.html.slim
.card
  .card-header
    .d-flex
      .h4.mr-auto Payments

  .card-body.p-0
    - if @payments.any?
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.table-sm
          thead.thead-light
            tr
              th = sortable 'Payee', :payee
              th = sortable 'Schedule', :schedule
              th = sortable 'Date', :date
              th = sortable 'Due Date', :due_date
              th = sortable 'Amount', :amount
          tbody
            - @payments.each do |payment|
              tr
                td = link_to payment.schedule.payee.name, payee_path(payment.schedule.payee)
                td = link_to payment.payment.schedule.name, schedule_path(payment.schedule)
                td = payment.date
                td = payment.due_date
                td.text-right = payment.amount
        = paginate  @payments
    - else
      .h5.text-center.p-3 There are currenty no payments in the system

app/views/payments/new.html.slim
.card
  .card-header
    .d-felx
      .h4 New Payment
  .card-body
    == render partial: 'form', locals: { payment: @payment, schedule: @schedule }