config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :payees do
    resources :schedules, shallow: true, except: :index do
      resources :payments, shallow: true, except: %i[index show]
    end
  end

  get 'calendar', to: 'calendar#index'
  get 'calendar/events', to: 'calendar#events'
  get 'payments', to: 'payments#index'

  root 'calendar#index'
end

app/models/payee.rb
# frozen_string_literal: true

# Model for payees
class Payee < ApplicationRecord
  strip_attributes

  # Relations
  has_many :schedules, dependent: :destroy

  # Validations
  validates :name, presence: true, uniqueness: true, allow_blank: false
end

app/controllers/payees_controller.rb
# frozen_string_literal: true

# Controller for creating, modifying, and deleting payees
class PayeesController < ApplicationController
  before_action :set_payee, only: %i[show edit update destroy]

  # GET /payees
  # GET /payees.json
  def index
    @payees = Payee.all
                   .rezort(params[:sort], 'name ASC')
                   .page(params[:page])
                   .decorate
  end

  # GET /payees/new
  def new
    @payee = Payee.new
  end

  # GET /payees/1/edit
  def edit; end

  def show
    @payee = @payee.decorate
    @schedules = @payee.schedules
                       .rezort(params[:sort], 'start_date ASC')
                       .page(params[:page])
                       .decorate
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)

    respond_to do |format|
      if @payee.save
        format.html { redirect_to @payee, notice: 'Payee was successfully created.' }
        format.json { render :show, status: :created, location: @payee }
      else
        format.html { render :new }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to payee_url(@payee), notice: 'Payee was successfully updated.' }
        format.json { render :show, status: :ok, location: @payee }
      else
        format.html { render :edit }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    respond_to do |format|
      format.html { redirect_to payees_url, notice: 'Payee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payee
    @payee = Payee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payee_params
    params.require(:payee).permit(:name, :nickname, :website, :phone_number, :description)
  end
end

app/helpers/payees_helper.rb
# frozen_string_literal: true

# These helpers used in views for payees
module PayeesHelper
  def payee_delete_modal_params
    { confirm: 'Deleting this payee will also permanently delete all associated schedules with ' \
               'their payment histories. Are you sure you want to permanently delete this payee?',
      commit: 'Delete Payee' }
  end
end

app/views/payees/_form.html.slim
= simple_form_for(payee, wrapper: :horizontal_form) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :nickname
    = f.input :website
    = f.input :phone_number
    = f.input :description

  .form-actions
    .form-group.row.mb-0
      .col-sm-9.offset-sm-3
        = f.button :submit, class: 'btn-primary'
        = f.button :button, 'Reset Form', type: 'reset', class: 'btn-outline-secondary'
        = button_cancel payee, (payee.persisted? ? 'Back to Payee Details' : 'Back to Payees List')

app/views/payees/edit.html.slim
.card
  .card-header
    .d-flex
      .h4 Payee
  .card-body
    == render partial: 'form', locals: { payee: @payee }

app/views/payees/index.html.slim
.card
  .card-header
    .d-flex
      .h4.mr-auto Payees
      = button_success 'New Payee', new_payee_path, 'plus'
  .card-body.p-0
    - if @payees.any?
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.table-sm
          thead.thead-light
            tr
              th = sortable 'Name', :name
              th = sortable 'Nickname', :nickname
              th = sortable 'Website', :website
              th = sortable 'Phone Number', :phone_number
              th Actions
          tbody
            - @payees.each do |payee|
              tr
                td = payee.name
                td = payee.nickname
                td = sanitize payee.website
                td = payee.phone_number
                td.text-nowrap
                  = button_primary 'Details', payee_path(payee), 'info-circle'
                  = button_danger 'Delete', payee, 'trash',
                      data: payee_delete_modal_params,
                      method: :delete
        = paginate @payees
    - else
      .h5.text-center.p-3 Create a payee to get started

app/views/payees/new.html.slim
.card
  .card-header
    .d-felx
      .h4 New Payee
  .card-body
    == render partial: 'form', locals: { payee: @payee }

app/views/payees/show.html.slim
.card
  .card-header
    .h4 Payee Details
  .card-body
    .form-group.row
      .col-sm-3.col-form-label = Payee.human_attribute_name('name')
      .col-sm-9.form-control-plaintext = @payee.name
    .form-group.row
      .col-sm-3.col-form-label = Payee.human_attribute_name('nickname')
      .col-sm-9.form-control-plaintext = @payee.nickname
    .form-group.row
      .col-sm-3.col-form-label = Payee.human_attribute_name('website')
      .col-sm-9.form-control-plaintext = sanitize @payee.website
    .form-group.row
      .col-sm-3.col-form-label = Payee.human_attribute_name('phone_number')
      .col-sm-9.form-control-plaintext = @payee.phone_number
    .form-group.row
      .col-sm-3.col-form-label = Payee.human_attribute_name('description')
      .col-sm-9
        pre.scrollable = @payee.description
    .form-group.row
      .col-sm-9.offset-sm-3
        = button_primary 'Edit Payee', edit_payee_path(@payee), 'edit'
        = button_danger 'Delete Payee', @payee, 'trash',
            data: payee_delete_modal_params,
            method: :delete
        = button_cancel payees_path, 'Back to Payees List'

br

= render partial: 'schedules/index', locals: { payee: @payee, schedules: @schedules }